[workspace]
resolver = "3"
members = ["cli", "github", "jj", "stacks"]

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.6.1", features = ["derive"] }
futures = "0.3"
http = "1.4.0"
jj-lib = { version = "0.41.0", features = ["git"] }
octocrab = "0.51.0"
once_cell = "1.21.4"
regex = "1.12.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
